apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: testers.extensions.practice.com
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: extensions.practice.com
  # 列举此 CustomResourceDefinition 所支持的版本
  versions:
    - name: v1
      # 是否有效
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: # 下面填的crd的字段
            spec:
              type: object
              properties:
                version:
                  type: string
  # 范围是属于namespace的 ,可以是 Namespaced 或 Cluster
  scope: Namespaced
  names:
    # 复数名
    plural: testers
    # 单数名
    singular: tester
    # 类型名
    kind: Tester
    listKind: TesterList
    # kind的简称，就像service的简称是svc
    shortNames:
      - route